version: "3.9"

services:
  warp-unlimited:
    image: ghcr.io/thecaduceus/warp-unlimited-docker:okteto
    container_name: warp-unlimited-okteto
    environment:
      - WARP_CLIENT_ID=${WARP_CLIENT_ID}
      - SEND_LOG=${SEND_LOG}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - HIDE_WC_ID=${HIDE_WC_ID}
    ports:
      - 8080:8080
    restart: unless-stopped
